<?php
class Action
{
    use Getter;

    private $_method;
    private $_args;
    private $_pathVars;
    private $_httpHeaders = Sys::NO_CACHE_HEADERS;
    private $_content;

    protected $_title;

    private static function loadActionClass($class)
    {
        $file = Str::classToFile($class) . '_action.php';
        if (is_file(ACTIONS_PATH . '/' . $file)) { // In user action path.
            require_once ACTIONS_PATH . '/' . $file;
        } else if (is_file(__DIR__ . '/actions/' . $file)) { // In sys action path.
            require_once __DIR__ . '/actions/' . $file;
        } else {
            throw new Exception('Cannot find action class "' . $class . '".');
        }
        $class .= 'Action';
        return new $class;
    }

    public static function get($action, $args)
    {
        if (!empty($action)) {
            list($class, $method) = explode('::', $action, 2);
            if (!empty($method)) {
                $actions = self::loadActionClass($class);
                if (!$actions instanceof Action) {
                    throw new Exception('Actions must inhrerit class "' . self::class . '".');
                }
                $actions->_method = $method;
            } else {
                $actions = new Action;
                $actions->_method = $action;
            }
        } else {
            $actions = new Action;
            $actions->_method = 'default';
        }
        $actions->_args = $args;
        return $actions;
    }

    public function cook($pathVars)
    {
        $this->_pathVars = $pathVars;
        $method = $this->_method;
        if (!method_exists($this, $method)) {
            throw new Exception('Cannot find action "' . get_class($this) . '::' . $method . '".');
        }
        $content = Common::getOutput([$this, $method], $this->_args);
        if (Server::isAjaxRequest()) {
            echo $content;
            exit;
        }
        $this->_content = $content;
    }

    public function default(...$args)
    {
        $this->_title = 'default';
        echo <<<EOS
        <h1>default</h1>
        <p class="sys">
        Generated by default action of <a href="https://github.com/lasyard/lasys" target="_blank">Lasys</a>.
        </p>
        EOS;
        echo '<p>pathVars = ';
        print_r($this->pathVars);
        echo '</p>';
        echo '<p>args = ';
        print_r($args);
        echo '</p>';
    }
}
