<?php
class Action
{
    use Getter;

    private $_method;
    private $_httpHeaders = Sys::NO_CACHE_HEADERS;
    private $_content;

    protected $_title;
    protected $_args;

    private static function loadActionClass($class)
    {
        $file = Str::classToFile($class);
        if (is_file(ACTIONS_PATH . '/' . $file)) { // In user action path.
            require_once ACTIONS_PATH . '/' . $file;
        } else if (is_file(__DIR__ . '/actions/' . $file)) { // In sys action path.
            require_once __DIR__ . '/actions/' . $file;
        } else {
            throw new Exception('Cannot find action class "' . $class . '".');
        }
        return new $class;
    }

    public static function get($action)
    {
        if (!empty($action)) {
            list($class, $method) = explode('::', $action, 2);
            if (!empty($method)) {
                $actions = self::loadActionClass($class);
                if (!$actions instanceof Action) {
                    throw new Exception('Actions must inhrerit class "' . self::class . '".');
                }
                $actions->_method = $method;
            } else {
                $actions = new Action;
                $actions->_method = $action;
            }
        } else {
            $actions = new Action;
            $actions->_method = 'default';
        }
        return $actions;
    }

    public function cook($args)
    {
        list($method, $paras) = Str::splitFunParas($this->_method);
        if (!method_exists($this, $method)) {
            throw new Exception('Cannot find action "' . get_class($this) . '::' . $method . '".');
        }
        $this->_args = $args;
        ob_start();
        try {
            call_user_func_array([$this, $method], $paras);
        } catch (Exception $e) {
            ob_get_clean();
            throw $e;
        }
        $this->_content = ob_get_clean();
    }

    public function default(...$paras)
    {
        $this->_title = 'default';
        echo <<<EOS
        <h1>default</h1>
        <p class="sys">
        Generated by default action of <a href="https://github.com/lasyard/lasys" target="_blank">Lasys</a>.
        </p>
        EOS;
        echo '<p>args = ';
        print_r($this->_args);
        echo '</p>';
        echo '<p>paras = ';
        print_r($paras);
        echo '</p>';
    }
}
