<?php
class Action
{
    use Getter;

    private $_method;
    private $_httpHeaders = Sys::NO_CACHE_HEADERS;
    private $_title;
    private $_content;

    public static function get($action)
    {
        list($class, $method) = explode('::', $action, 2);
        $action = new $class;
        if (!$action instanceof Action) {
            throw new Exception('Actions must inhrerit class "' . self::class . '".');
        }
        $action->_method = $method;
        return $action;
    }

    public function cook($args)
    {
        if (!method_exists($this, $this->_method)) {
            throw new Exception('Cannot find action "' . get_class($this) . '::' . $this->_method . '".');
        }
        ob_start();
        try {
            call_user_func_array([$this, $this->_method], $args);
        } catch (Exception $e) {
            ob_get_clean();
            throw $e;
        }
        $this->_content  = ob_get_clean();
    }

    public function default(...$args)
    {
        $this->_title = 'default';
        echo <<<EOS
        <h1>default</h1>
        <p class="sys">
        Generated by default action of <a href="https://github.com/lasyard/lasys" target="_blank">Lasys</a>.
        </p>
        EOS;
        echo 'args = ';
        print_r($args);
    }
}
